#!/usr/bin/env bash
# Prepares the Oracle container for Debezium LogMiner capture. Idempotent: safe to re-run.
# Sequence verified on virag/oracle-19.3.0-ee(-arm64): recovery area first, then the
# ARCHIVELOG flip, supplemental logging, the LogMiner user, and the demo schema.
set -euo pipefail

ORACLE_CONTAINER="${ORACLE_CONTAINER:-oracle19c-demo}"

current_log_mode() {
    docker exec -i "$ORACLE_CONTAINER" bash -c 'sqlplus -S / as sysdba <<SQL
SET HEADING OFF FEEDBACK OFF
SELECT log_mode FROM v\$database;
SQL' 2>/dev/null | tr -d "[:space:]"
}

already_archivelog() {
    # Exact match: NOARCHIVELOG contains ARCHIVELOG as a substring, so no grep here.
    [ "$(current_log_mode)" = "ARCHIVELOG" ]
}

if already_archivelog; then
    echo "[setup-oracle] ARCHIVELOG already enabled, skipping database restart"
else
    echo "[setup-oracle] Enabling ARCHIVELOG mode (requires a database restart)..."
    # The recovery area directory must exist before the restart or STARTUP fails.
    docker exec "$ORACLE_CONTAINER" mkdir -p /opt/oracle/oradata/recovery_area
    docker exec -i "$ORACLE_CONTAINER" bash -c 'sqlplus -S / as sysdba <<SQL
ALTER SYSTEM SET db_recovery_file_dest_size = 10G;
ALTER SYSTEM SET db_recovery_file_dest = '"'"'/opt/oracle/oradata/recovery_area'"'"' SCOPE=spfile;
SHUTDOWN IMMEDIATE
STARTUP MOUNT
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;
ALTER PLUGGABLE DATABASE ALL OPEN;
SQL'
    already_archivelog || { echo "[setup-oracle] ERROR: log mode is still $(current_log_mode) after the restart"; exit 1; }
    echo "[setup-oracle] ARCHIVELOG enabled"
fi

echo "[setup-oracle] Enabling supplemental logging and creating the LogMiner user..."
docker exec -i "$ORACLE_CONTAINER" bash -c 'sqlplus -S / as sysdba <<SQL
WHENEVER SQLERROR CONTINUE
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
CREATE TABLESPACE logminer_tbs DATAFILE '"'"'/opt/oracle/oradata/ORCLCDB/logminer_tbs.dbf'"'"' SIZE 25M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
ALTER SESSION SET CONTAINER = ORCLPDB1;
CREATE TABLESPACE logminer_tbs DATAFILE '"'"'/opt/oracle/oradata/ORCLCDB/ORCLPDB1/logminer_tbs.dbf'"'"' SIZE 25M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
ALTER SESSION SET CONTAINER = CDB\$ROOT;
CREATE USER c##dbzuser IDENTIFIED BY dbz DEFAULT TABLESPACE logminer_tbs QUOTA UNLIMITED ON logminer_tbs CONTAINER=ALL;
GRANT CREATE SESSION TO c##dbzuser CONTAINER=ALL;
GRANT SET CONTAINER TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_\$DATABASE TO c##dbzuser CONTAINER=ALL;
GRANT FLASHBACK ANY TABLE TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ANY TABLE TO c##dbzuser CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE TO c##dbzuser CONTAINER=ALL;
GRANT EXECUTE_CATALOG_ROLE TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO c##dbzuser CONTAINER=ALL;
GRANT LOGMINING TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ANY DICTIONARY TO c##dbzuser CONTAINER=ALL;
GRANT CREATE TABLE TO c##dbzuser CONTAINER=ALL;
GRANT LOCK ANY TABLE TO c##dbzuser CONTAINER=ALL;
GRANT CREATE SEQUENCE TO c##dbzuser CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR TO c##dbzuser CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR_D TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_\$LOG TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_\$LOG_HISTORY TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_\$LOGMNR_LOGS TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_\$LOGMNR_CONTENTS TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_\$LOGMNR_PARAMETERS TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_\$LOGFILE TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_\$ARCHIVED_LOG TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_\$ARCHIVE_DEST_STATUS TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_\$TRANSACTION TO c##dbzuser CONTAINER=ALL;
SQL'

echo "[setup-oracle] Creating the demo schema in ORCLPDB1..."
docker exec -i "$ORACLE_CONTAINER" bash -c 'sqlplus -S / as sysdba <<SQL
WHENEVER SQLERROR CONTINUE
ALTER SESSION SET CONTAINER = ORCLPDB1;
CREATE USER debezium IDENTIFIED BY dbz DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO debezium;
CREATE TABLE debezium.customers (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100),
    tier VARCHAR2(20) DEFAULT '"'"'standard'"'"',
    balance NUMBER(12,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE debezium.customers ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
DECLARE
    n NUMBER;
BEGIN
    SELECT COUNT(*) INTO n FROM debezium.customers;
    IF n = 0 THEN
        INSERT INTO debezium.customers (name, email, tier, balance) VALUES ('"'"'Alice Johnson'"'"', '"'"'alice@example.com'"'"', '"'"'gold'"'"', 1250.50);
        INSERT INTO debezium.customers (name, email, tier, balance) VALUES ('"'"'Bob Smith'"'"', '"'"'bob@example.com'"'"', '"'"'standard'"'"', 310.00);
        INSERT INTO debezium.customers (name, email, tier, balance) VALUES ('"'"'Carol Davis'"'"', '"'"'carol@example.com'"'"', '"'"'platinum'"'"', 9875.25);
        COMMIT;
    END IF;
END;
/
SQL'
echo "[setup-oracle] Done"
