-- Enable rangefeed (required for changefeeds)
SET CLUSTER SETTING kv.rangefeed.enabled = true;

-- Create demo database. The 'demo' SQL user is mapped 1:1 to the cert with
-- CN=demo (generated by generate-certs.sh -> certs/crdb/client.demo.crt).
-- Because CockroachDB is in secure mode, that cert *is* the authentication
-- credential — no password is needed for the connector.
CREATE DATABASE IF NOT EXISTS demodb;
CREATE USER IF NOT EXISTS demo;
GRANT CONNECT ON DATABASE demodb TO demo;
GRANT SYSTEM VIEWCLUSTERSETTING TO demo;
GRANT SYSTEM VIEWJOB TO demo;

USE demodb;

CREATE TABLE IF NOT EXISTS orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_number STRING UNIQUE NOT NULL,
    customer_name STRING NOT NULL,
    amount DECIMAL(12,2) NOT NULL CHECK (amount >= 0),
    status STRING NOT NULL DEFAULT 'pending',
    -- NOT NULL JSONB coverage: exercises the optional JSONB field mapping (debezium/dbz#2253)
    metadata JSONB NOT NULL DEFAULT '{}',
    -- High-precision DECIMAL coverage: exercises exact decimal passthrough (debezium/dbz#2256)
    precise_qty DECIMAL(28,18) NOT NULL DEFAULT 0.0,
    created_at TIMESTAMPTZ DEFAULT current_timestamp()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE orders TO demo;
GRANT CHANGEFEED ON TABLE orders TO demo;

INSERT INTO orders (order_number, customer_name, amount, status) VALUES
    ('ORD-MTLS-001', 'Alice Johnson', 129.99, 'confirmed'),
    ('ORD-MTLS-002', 'Bob Smith',     249.50, 'pending'),
    ('ORD-MTLS-003', 'Carol Davis',    34.99, 'shipped');
